// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("rescript/lib/js/caml_option.js");

function SVGCheck(Props) {
  var width = Props.width;
  var height = Props.height;
  var fill = Props.fill;
  var stroke = Props.stroke;
  var tmp = {
    focusable: "false",
    viewBox: "0 0 24 24"
  };
  if (height !== undefined) {
    tmp.height = Caml_option.valFromOption(height);
  }
  if (width !== undefined) {
    tmp.width = Caml_option.valFromOption(width);
  }
  if (fill !== undefined) {
    tmp.fill = Caml_option.valFromOption(fill);
  }
  if (stroke !== undefined) {
    tmp.stroke = Caml_option.valFromOption(stroke);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"
                }));
}

var make = SVGCheck;

exports.make = make;
/* react Not a pure module */
