// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var DockerListModuleCss = require("./DockerList.module.css");

var styles = DockerListModuleCss;

function ButtonWithConfirm(Props) {
  var onClick = Props.onClick;
  var status = Props.status;
  var question = Props.question;
  var classNameOpt = Props.className;
  var confirmButtonStyle = Props.confirmButtonStyle;
  var children = Props.children;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var dialogEl = React.useRef(null);
  var openDialog = function (_event) {
    return Belt_Option.forEach(Caml_option.nullable_to_opt(dialogEl.current), (function (input) {
                  input.showModal();
                  
                }));
  };
  var closeDialog = function (_event) {
    return Belt_Option.forEach(Caml_option.nullable_to_opt(dialogEl.current), (function (input) {
                  input.close();
                  
                }));
  };
  return React.createElement(React.Fragment, undefined, React.createElement("button", {
                  className: className,
                  onClick: openDialog
                }, children), React.createElement("dialog", {
                  ref: dialogEl
                }, React.createElement("p", undefined, status), React.createElement("p", undefined, question), React.createElement("div", {
                      className: styles["dialog-actions"]
                    }, React.createElement("button", {
                          className: styles["mui-button"],
                          onClick: closeDialog
                        }, "cancel"), React.createElement("button", {
                          className: styles["mui-button"],
                          style: confirmButtonStyle,
                          onClick: (function ($$event) {
                              Curry._1(onClick, $$event);
                              return closeDialog(undefined);
                            })
                        }, "OK"))));
}

var make = ButtonWithConfirm;

exports.styles = styles;
exports.make = make;
/* styles Not a pure module */
