// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as DockerListModuleCss from "./DockerList.module.css";

var styles = DockerListModuleCss;

function ButtonWithConfirm(Props) {
  var onClick = Props.onClick;
  var question = Props.question;
  var classNameOpt = Props.className;
  var confirmButtonStyle = Props.confirmButtonStyle;
  var children = Props.children;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var dialogEl = React.useRef(null);
  var openDialog = function (_event) {
    return Belt_Option.forEach(Caml_option.nullable_to_opt(dialogEl.current), (function (input) {
                  input.showModal();
                  
                }));
  };
  var closeDialog = function (_event) {
    return Belt_Option.forEach(Caml_option.nullable_to_opt(dialogEl.current), (function (input) {
                  input.close();
                  
                }));
  };
  return React.createElement(React.Fragment, undefined, React.createElement("button", {
                  className: className,
                  onClick: openDialog
                }, children), React.createElement("dialog", {
                  ref: dialogEl
                }, React.createElement("p", undefined, question), React.createElement("div", {
                      className: styles["dialog-actions"]
                    }, React.createElement("button", {
                          className: styles["mui-button"],
                          onClick: closeDialog
                        }, "cancel"), React.createElement("button", {
                          className: styles["mui-button"],
                          style: confirmButtonStyle,
                          onClick: (function ($$event) {
                              Curry._1(onClick, $$event);
                              return closeDialog(undefined);
                            })
                        }, "OK"))));
}

var make = ButtonWithConfirm;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
