// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as DockerListModuleCss from "./DockerList.module.css";

var styles = DockerListModuleCss;

function ConfirmAction(Props) {
  var onClick = Props.onClick;
  var question = Props.question;
  var classNameOpt = Props.className;
  var confirmButtonColorOpt = Props.confirmButtonColor;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var confirmButtonColor = confirmButtonColorOpt !== undefined ? confirmButtonColorOpt : "";
  var dialogEl = React.useRef(null);
  var openDialog = function (_event) {
    return Belt_Option.forEach(Caml_option.nullable_to_opt(dialogEl.current), (function (input) {
                  input.showModal();
                  
                }));
  };
  var closeDialog = function (_event) {
    return Belt_Option.forEach(Caml_option.nullable_to_opt(dialogEl.current), (function (input) {
                  input.close();
                  
                }));
  };
  return React.createElement(React.Fragment, undefined, React.createElement("button", {
                  className: className,
                  onClick: openDialog
                }, "modal"), React.createElement("dialog", {
                  ref: dialogEl
                }, question, React.createElement("button", {
                      className: styles.button + " " + styles.off,
                      onClick: closeDialog
                    }, "cancel"), React.createElement("button", {
                      className: styles.button,
                      style: {
                        backgroundColor: confirmButtonColor
                      },
                      onClick: onClick
                    }, "OK")));
}

var make = ConfirmAction;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
