// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as DockerListModuleCss from "./DockerList.module.css";
import * as ReasonApi$MdworldHomeremoteDockerlist from "./ReasonApi.bs.js";
import * as ConfirmAction$MdworldHomeremoteDockerlist from "./ConfirmAction.bs.js";

var styles = DockerListModuleCss;

function DockerList$DockerListMod(Props) {
  var match = React.useState(function () {
        return [];
      });
  var setContainers = match[1];
  React.useEffect((function () {
          ReasonApi$MdworldHomeremoteDockerlist.getDockerList(undefined).then(function (containerList) {
                Curry._1(setContainers, (function (_prev) {
                        return containerList;
                      }));
                return Promise.resolve(containerList);
              });
          
        }), []);
  var handleClickFetch = function (id, _event) {
    console.log("handleClickFetch");
    ReasonApi$MdworldHomeremoteDockerlist.getDockerList(undefined).then(function (containerList) {
          Curry._1(setContainers, (function (_prev) {
                  return containerList;
                }));
          return Promise.resolve(containerList);
        });
    ReasonApi$MdworldHomeremoteDockerlist.startContainer(id).then(function (containerList) {
          Curry._1(setContainers, (function (_prev) {
                  return containerList;
                }));
          return Promise.resolve(containerList);
        });
    
  };
  var dockerContainersElems = match[0].map(function (dockerContainer) {
        var state = dockerContainer.State;
        var className = styles["button-list-item"] + " " + styles["mui-button"] + " " + (
          state === "running" ? styles["button-success"] : ""
        );
        var name = dockerContainer.Names.map(function (name) {
                return name.slice(1);
              }).join(" ");
        var partial_arg = dockerContainer.Id;
        return React.createElement(ConfirmAction$MdworldHomeremoteDockerlist.make, {
                    onClick: (function (param) {
                        return handleClickFetch(partial_arg, param);
                      }),
                    question: "Do you want to **turn on** " + name + "?",
                    className: className,
                    confirmButtonStyle: {
                      backgroundColor: "darkblue",
                      color: "white"
                    },
                    children: null
                  }, React.createElement("h1", undefined, name), React.createElement("p", undefined, dockerContainer.Status));
      });
  return React.createElement("div", {
              className: styles.root
            }, React.createElement("div", {
                  className: styles["button-list"]
                }, React.createElement(ConfirmAction$MdworldHomeremoteDockerlist.make, {
                      onClick: (function (param) {
                          return handleClickFetch("some-id", param);
                        }),
                      question: "turn on ?? such a long text oh wow so long wow wow wow wow wow",
                      className: styles["button-list-item"] + " " + styles["mui-button"],
                      confirmButtonStyle: {
                        backgroundColor: "darkblue",
                        color: "white"
                      },
                      children: "modal"
                    }), dockerContainersElems), React.createElement("div", {
                  className: styles["button-list"],
                  style: {
                    marginTop: "2rem"
                  }
                }, React.createElement("button", {
                      className: styles["mui-button"],
                      onClick: (function (param) {
                          return handleClickFetch("some-id", param);
                        })
                    }, "modal"), React.createElement("button", {
                      className: styles["mui-button"] + " " + styles["button-error"],
                      onClick: (function (param) {
                          return handleClickFetch("some-id", param);
                        })
                    }, React.createElement("h1", undefined, "Errrr"), React.createElement("p", undefined, "Borked"))));
}

var DockerListMod = {
  make: DockerList$DockerListMod
};

export {
  styles ,
  DockerListMod ,
  
}
/* styles Not a pure module */
