// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

function getDogs(address, onDone, onError) {
  var request = new XMLHttpRequest();
  request.addEventListener("load", (function (param) {
          return Curry._1(onDone, JSON.parse(request.response));
        }));
  request.addEventListener("error", (function (param) {
          return Curry._1(onError, request.status);
        }));
  request.open("GET", "https://dog.ceo/api/breeds/image/random/" + address);
  request.send();
  
}

function getDogsAndPrint(param) {
  return getDogs("3", (function (response) {
                console.log("weird", response.message);
                
              }), (function (x) {
                console.log("Error logging: " + String(x));
                
              }));
}

function getDogsAndShow(show) {
  return getDogs("1", (function (response) {
                console.log("weird", response.message);
                return Curry._1(show, Caml_array.get(response.message, 0));
              }), (function (x) {
                console.log("Error logging: " + String(x));
                
              }));
}

var Api = {
  getDogs: getDogs,
  getDogsAndPrint: getDogsAndPrint,
  getDogsAndShow: getDogsAndShow
};

export {
  Api ,
  
}
/* No side effect */
