// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Core from "@material-ui/core";
import * as MaterialUi_Checkbox from "@jsiebern/bs-material-ui/src/MaterialUi_Checkbox.bs.js";
import * as MaterialUi_IconButton from "@jsiebern/bs-material-ui/src/MaterialUi_IconButton.bs.js";
import * as DockerListModuleCss from "./DockerList.module.css";
import $$Error from "@material-ui/icons/Error";

var styles = DockerListModuleCss;

var ErrorIcon = {};

function DockerListItem(Props) {
  var container = Props.container;
  var onSelect = Props.onSelect;
  var id = container.Id;
  var state = container.State;
  var status = container.Status;
  var isRunning = state === "running";
  var isExited = state === "exited";
  var isUnexpected = !isRunning && !isExited;
  var name = container.Names.map(function (name) {
          return name.slice(1);
        }).join(" ");
  return React.createElement("div", undefined, React.createElement(Core.ListItem, {
                  button: true,
                  children: null,
                  dense: true,
                  onClick: (function (_ev) {
                      return Curry._1(onSelect, /* DockerContainer */{
                                  _0: container
                                });
                    })
                }, React.createElement(Core.ListItemIcon, {
                      children: isUnexpected ? React.createElement(Core.ListItemIcon, {
                              children: React.createElement(Core.IconButton, {
                                    children: React.createElement($$Error, {
                                          color: "error"
                                        }),
                                    edge: MaterialUi_IconButton.Edge.start
                                  })
                            }) : React.createElement(Core.Checkbox, {
                              edge: MaterialUi_Checkbox.Edge.start,
                              checked: isRunning,
                              inputProps: {
                                "aria-labelledby": id
                              }
                            })
                    }), React.createElement(Core.ListItemText, {
                      primary: name,
                      secondary: status,
                      id: id
                    })));
}

var make = DockerListItem;

export {
  styles ,
  ErrorIcon ,
  make ,
  
}
/* styles Not a pure module */
