// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Js_exn from "rescript/lib/es6/js_exn.js";

function handleResponse(onError, errorMessage, promise) {
  var __x = promise.then(function (jsonResponse) {
        var response = JSON.parse(jsonResponse);
        if (response.status === "received") {
          return Promise.resolve(response.containers);
        } else {
          return Js_exn.raiseError("Error in response");
        }
      });
  return __x.catch(function (_err) {
              Curry._1(onError, errorMessage);
              return Promise.resolve([]);
            });
}

function getDockerList(url, onError) {
  return handleResponse(onError, "error in getDockerList", fetch(url + "/api/dockerlist").then(function (prim) {
                  return prim.text();
                }));
}

function startContainer(url, id, onError) {
  return handleResponse(onError, "error in startContainer", fetch(url + "/api/dockerlist/start/" + id).then(function (prim) {
                  return prim.text();
                }));
}

function stopContainer(url, id, onError) {
  return handleResponse(onError, "error in stopContainer", fetch(url + "/api/dockerlist/stop/" + id).then(function (prim) {
                  return prim.text();
                }));
}

export {
  handleResponse ,
  getDockerList ,
  startContainer ,
  stopContainer ,
  
}
/* No side effect */
