// Generated by ReScript, PLEASE EDIT WITH CARE


function myFunc(param) {
  return Promise.resolve({
              hd: "a",
              tl: /* [] */0
            });
}

function fetchDogs(param) {
  return fetch("https://dog.ceo/api/breeds/image/random/3").then(function (response) {
                  return response.json();
                }).then(function (jsonResponse) {
                return Promise.resolve(jsonResponse.message);
              }).catch(function (_err) {
              return Promise.resolve([]);
            });
}

export {
  myFunc ,
  fetchDogs ,
  
}
/* No side effect */
