// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Test$DockerListMod(Props) {
  var count = Props.count;
  var times = count !== 1 ? (
      count !== 2 ? String(count) + " times" : "twice"
    ) : "once";
  var msg = "Click me " + times;
  return React.createElement("button", undefined, msg);
}

var DockerListMod = {
  make: Test$DockerListMod
};

export {
  DockerListMod ,
  
}
/* react Not a pure module */
