// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as DockerListModuleCss from "./DockerList.module.css";

var styles = DockerListModuleCss;

function Test$DockerListMod(Props) {
  var count = Props.count;
  var times = count !== 1 ? (
      count !== 2 ? String(count) + " times" : "twice"
    ) : "once";
  var msg = "Click me " + times;
  return React.createElement("button", {
              className: styles.root
            }, msg);
}

var DockerListMod = {
  make: Test$DockerListMod
};

export {
  styles ,
  DockerListMod ,
  
}
/* styles Not a pure module */
